@extends('backoffice.master')
@section('header')
    @parent
@endsection
@section('sidebar')
    @parent
@endsection
@section('content')
@endsection
@section('footer')
    @parent
@endsection
